# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_id',
        ),
        migrations.AddField(
            model_name='team',
            name='team_hint_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
