# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt_app', '0004_auto_20170121_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
