# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt_app', '0005_team_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'media/'),
        ),
    ]
