# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt_app', '0006_auto_20170121_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
