# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt_app', '0007_auto_20170122_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_photo',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
